apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-chall-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-chall
  template:
    metadata:
      labels:
        app: sre-chall
    spec:
      containers:
      - name: sre-chall
        image: bvink0209/sre:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sre-chall-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: sre-chall
